name: Registry Finder Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build Executable
      run: go build -a -ldflags="-s -w -H windowsgui -extldflags '-O2'" -o registry-finder-gui.exe ./main.go

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: registry-finder-gui
        path: registry-finder-gui.exe
